# Generated by Django 3.1 on 2020-08-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0007_auto_20180812_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
