# Generated by Django 3.1 on 2020-08-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0008_auto_20200823_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='semantic',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
