# Generated by Django 3.1 on 2020-08-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0009_essay_semantic'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='tense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='essay',
            name='wordcount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
